#!/usr/bin/env bash
#  Script bash gives you information about the Best school file
if [ -e bestschool ]
then
    echo "bestschool file exists"
    if [ -s bestschool ]
    then
echo "bestschool file is not empty"
    else
echo "bestschool file is empty"
    fi
    if [ -f bestschool ]
    then
echo "bestschool is a regular file"
    fi
else
    echo "bestschool file does not exist"
fi
